Repository kubernetes-client/javascript, pull requests merged in 2018-08, with the labels that each got.

#70 Update gitignore.
  .gitignore
Labels: cncf-cla: yes, size/XS

#71 Rev the release version.
  node-client/package.json
Labels: cncf-cla: yes, size/XS

#72 Some web sockets fixes.
  node-client/src/attach.ts
  node-client/src/config_types.ts
  node-client/src/web-socket-handler.ts
Labels: cncf-cla: yes, size/M

#69 fix(websockethandler): fix buffer init in handleStandardInput
  node-client/src/web-socket-handler.ts
Labels: cncf-cla: yes, size/XS

#77 fix `we need a path` error
  node-client/src/config.ts
Labels: cncf-cla: yes, size/XS

#78 Add some build scripts and rev the version.
  node-client/build-package.sh
  node-client/package.json
  node-client/push-package.sh
Labels: cncf-cla: yes, size/S

#79 Add CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: cncf-cla: yes, size/S

#80 Add OWNERS file
  OWNERS
Labels: cncf-cla: yes, size/XS

#84 Add several new options for creating KubeConfig objects.
  node-client/src/config.ts
  node-client/src/config_test.ts
Labels: cncf-cla: yes, size/M

#85 Add a travis config.
  .travis.yml
Labels: cncf-cla: yes, size/S

#86 Add tslint validation to travis.
  .travis.yml
  node-client/src/attach.ts
  node-client/src/web-socket-handler.ts
Labels: cncf-cla: yes, size/XS

#91 Update dependency versions.
  node-client/package.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#92 Add better functionality for instantiating other API clients.
  README.md
  examples/example.js
  examples/in-cluster.js
  examples/namespace.js
  examples/typescript/attach/attach-example.ts
  examples/typescript/exec/exec-example.ts
  examples/typescript/simple/example.ts
  examples/typescript/watch/watch-example.ts
  node-client/package.json
  node-client/src/config.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#93 Update README with build status and client status.
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#89 Remove auth-wrapper as it's no longer needed.
  node-client/src/auth-wrapper.ts
  node-client/src/config.ts
Labels: approved, cncf-cla: yes, lgtm, size/M
