Repository kubernetes-client/javascript, pull requests merged in 2018-09, with the labels that each got.

#98 Rev to 0.6.0
  node-client/package.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#90 Remove custom fromCluster logic.
  node-client/src/config.ts
Labels: approved, cncf-cla: yes, lgtm, size/S

#99 Feature/api config helpers
  node-client/package-lock.json
  node-client/src/config.ts
Labels: approved, cncf-cla: yes, lgtm, size/M
