Repository kubernetes-client/javascript, pull requests merged in 2018-11, with the labels that each got.

#142 Try to load kubeconfig from wsl if present.
  package-lock.json
  src/config.ts
Labels: approved, cncf-cla: yes, lgtm, size/S

#148 watch method crash on unexpected objects
  src/watch.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#147 Fixes to be more lenient on configs without users.
  src/config.ts
  src/config_test.ts
  src/config_types.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#150 Improve tests.
  package.json
  src/web-socket-handler.ts
  src/web-socket-handler_test.ts
Labels: approved, cncf-cla: yes, lgtm, size/L

#153 Add some simple YAML load/dump helpers and an example.
  examples/yaml-example.js
  src/yaml.ts
  src/yaml_test.ts
Labels: approved, cncf-cla: yes, lgtm, size/M
