Repository kubernetes-client/javascript, pull requests merged in 2018-07, with the labels that each got.

#51 fix token refresh for GKE on Windows
  node-client/src/config.ts
Labels: cncf-cla: yes, size/XS

#54 fix: parse insecure-skip-tls-verify correctly
  node-client/src/config_test.ts
  node-client/src/config_types.ts
  node-client/testdata/kubeconfig.yaml
Labels: cncf-cla: yes

#58 Add loadFromCluster to KubeConfig object, and an example of how to use.
  examples/in-cluster.js
  node-client/package.json
  node-client/src/config.ts
Labels: cncf-cla: yes, size/M

#60 Add tslint validation.
  node-client/package.json
  node-client/src/attach.ts
  node-client/src/auth-wrapper.ts
  node-client/src/config.ts
  node-client/src/config_test.ts
  node-client/src/config_types.ts
  node-client/src/exec.ts
  node-client/src/watch.ts
  node-client/src/web-socket-handler.ts
  node-client/tslint.json
Labels: cncf-cla: yes, size/XL

#61 node-client/src: change license from Unlicense to Apache-2.0
  node-client/src/package.json
Labels: cncf-cla: yes, size/XS

#63 Fix node deprecation warning on Buffer constructor
  node-client/src/config.ts
  node-client/src/web-socket-handler.ts
Labels: cncf-cla: yes, size/XS

#64 Regenerate for 1.11.2
  .gitignore
  README.md
  node-client/src/.gitignore
  node-client/src/api.ts
  node-client/src/git_push.sh
  node-client/src/package.json
  node-client/src/swagger.json
  node-client/src/swagger.json.unprocessed
  node-client/src/tsconfig.json
  node-client/src/typings.json
  settings
Labels: cncf-cla: yes, size/XXL
