Repository kubernetes-client/javascript, pull requests merged in 2018-10, with the labels that each got.

#114 Security contacts file
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/S

#113 Fix buffer trim while sending websocket messages
  node-client/src/web-socket-handler.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#119 Fix a bug where attach didn't handle stdin. Add testing.
  node-client/coverage/attach.ts.html
  node-client/coverage/config.ts.html
  node-client/coverage/config_types.ts.html
  node-client/coverage/index.html
  node-client/coverage/index.ts.html
  node-client/coverage/lcov-report/attach.ts.html
  node-client/coverage/lcov-report/config.ts.html
  node-client/coverage/lcov-report/config_types.ts.html
  node-client/coverage/lcov-report/index.html
  node-client/coverage/lcov-report/index.ts.html
  node-client/coverage/lcov-report/portforward.ts.html
  node-client/coverage/lcov-report/web-socket-handler.ts.html
  node-client/coverage/lcov.info
  node-client/coverage/portforward.ts.html
  node-client/coverage/web-socket-handler.ts.html
  node-client/src/attach.ts
  node-client/src/attach_test.ts
  node-client/src/web-socket-handler.ts
Labels: approved, cncf-cla: yes, lgtm, size/XL

#127 Rev `request` library version to pick up downstream dependency fixes.
  node-client/package-lock.json
  node-client/package.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#109 Makes "unexpected event" error message more useful
  node-client/src/watch.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#126 Regenerate API to switch to IncomingMessage.
  node-client/src/api.ts
  node-client/src/swagger.json
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#130 Update version for a new release of the npm package.
  node-client/package.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#138 chore: update packages and package-lock
  node-client/package-lock.json
  node-client/package.json
  node-client/src/proto-client.ts
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#136 Update dependencies to add tslib
  node-client/package-lock.json
  node-client/package.json
Labels: approved, cncf-cla: yes, size/XS

#132 Fix electron issues
  node-client/package-lock.json
  node-client/package.json
  node-client/src/attach_test.ts
  node-client/src/config.ts
  node-client/src/config_test.ts
  node-client/src/exec.ts
  node-client/src/exec_test.ts
  node-client/src/portforward.ts
  node-client/src/web-socket-handler.ts
Labels: approved, cncf-cla: yes, lgtm, size/L
