Repository kubernetes-client/javascript, pull requests merged in 2019-03, with the labels that each got.

#204 Fix #187 (forward.portForward - Uncaught Error: not opened)
  src/portforward.ts
  src/web-socket-handler.ts
Labels: approved, cncf-cla: yes, lgtm, size/L

#182 Upgrade client badge to gold
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#217 Fix exec.
  src/cloud_auth.ts
  src/config.ts
  src/config_test.ts
  src/config_types.ts
  src/exec_auth.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#219 Assign value to exec attribute to fix exec auth issue
  src/config_types.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#211 add version check to ci
  .travis.yml
  version-check.js
Labels: approved, cncf-cla: yes, lgtm, size/S

#221 Improve docs for programatic configs.
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#222 Release 0.8.2
  .gitignore
  package-lock.json
  package.json
  push-package.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#223 Update dependencies.
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/XL

#226 Fix relative path loading.
  src/config.ts
  src/config_test.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#83 Fixes #82 Add a client for the pod read-log endpoint
  src/index.ts
  src/log.ts
Labels: approved, cncf-cla: yes, lgtm, size/M
