Repository kubernetes-client/javascript, pull requests merged in 2019-02, with the labels that each got.

#201 Remove unneeded deps
  package.json
  src/config.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#202 Move appropriate @types back to dependencies
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#195 Return connection in attach method
  src/attach.ts
Labels: cncf-cla: yes, lgtm, size/XS

#207 Rev version to 0.8.2 now that 0.8.1 is published.
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#179 fix: access-token does not get refreshed if not present
  src/cloud_auth.ts
  src/config_test.ts
Labels: approved, cncf-cla: yes, lgtm, size/L

#212 Feature/prettier
  .prettierignore
  README.md
  package-lock.json
  package.json
  src/attach.ts
  src/attach_test.ts
  src/cache.ts
  src/cache_test.ts
  src/cloud_auth.ts
  src/config.ts
  src/config_test.ts
  src/config_types.ts
  src/exec.ts
  src/exec_auth.ts
  src/exec_test.ts
  src/oidc_auth_test.ts
  src/portforward.ts
  src/portforward_test.ts
  src/watch.ts
  src/watch_test.ts
  src/web-socket-handler.ts
  src/web-socket-handler_test.ts
  src/yaml_test.ts
  tslint.json
Labels: approved, cncf-cla: yes, lgtm, size/XL

#210 Improve build and push scripts.
  build-package.sh
  pre-check.sh
  push-package.sh
Labels: approved, cncf-cla: yes, lgtm, size/M
