Repository kubernetes-client/javascript, pull requests merged in 2019-05, with the labels that each got.

#240 Support terminal resizes
  package.json
  src/attach.ts
  src/attach_test.ts
  src/exec.ts
  src/exec_test.ts
  src/terminal-size-queue.ts
  src/web-socket-handler.ts
  test/call-awaiter.ts
  test/index.ts
  test/match-buffer.ts
  test/resizable-writeable-stream-buffer.ts
Labels: approved, cncf-cla: yes, lgtm, size/L

#248 Switch from jsonpath to jsonpath-plus
  package-lock.json
  package.json
  src/cloud_auth.ts
Labels: approved, cncf-cla: yes, lgtm, size/L

#246 Fix env variables to include existing environment variables, then override
  .gitignore
  src/exec_auth.ts
  src/exec_auth_test.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#250 Handle JSON parse errors in watch implementation
  package-lock.json
  package.json
  src/watch.ts
  src/watch_test.ts
Labels: approved, cncf-cla: yes, lgtm, size/L

#252 Fix console output when running auth code
  src/exec_auth.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#253 Rev to version 0.9.0
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#254 Add more tests for password authentication.
  package-lock.json
  package.json
  src/config_test.ts
  src/integration_test.ts
  testdata/kubeconfig.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#257 Add pre-push check for tests and linter
  .travis.yml
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/L
