Repository kubernetes-client/javascript, pull requests merged in 2019-08, with the labels that each got.

#323 Add 'off' method to ListWatch and Informer which allows for the removal of callbacks
  src/cache.ts
  src/cache_test.ts
  src/informer.ts
Labels: approved, cncf-cla: yes, lgtm, size/L

#315 openapi-generator compiled code regenerated on 2019-08-05T09:13:38Z
  src/gen/model/runtimeRawExtension.ts
  src/gen/model/v1DaemonEndpoint.ts
  src/gen/model/v1beta1CustomResourceColumnDefinition.ts
Labels: approved, cncf-cla: yes, lgtm, size/S

#324 Make Informer and ListWatch start method async which resolves after the first list
  src/cache.ts
  src/cache_test.ts
  src/informer.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#319 Call watcher's done callback with correct statusMessage field on request error
  src/watch.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#316 Fixes path for openapi-generator output in README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#328 Convert `Authenticator.applyAuthentication` to return a `Promise<void>`
  src/auth.ts
  src/cloud_auth.ts
  src/config.ts
  src/config_test.ts
  src/proto-client.ts
  src/web-socket-handler.ts
  src/web-socket-handler_test.ts
Labels: approved, cncf-cla: yes, lgtm, size/L

#331 Remove duplicate variable definition in settings
  settings
Labels: approved, cncf-cla: yes, lgtm, size/XS

#330 Script for generating client code
  README.md
  generate-client.sh
  package.json
  settings
Labels: approved, cncf-cla: yes, lgtm, size/M

#333 Add a refreshing auth token for in-cluster configurations.
  src/auth.ts
  src/cloud_auth.ts
  src/config.ts
  src/config_test.ts
  src/exec_auth.ts
  src/exec_auth_test.ts
  src/file_auth.ts
  src/file_auth_test.ts
  src/oidc_auth.ts
  src/oidc_auth_test.ts
Labels: approved, cncf-cla: yes, lgtm, size/L

#334 add typedoc generation for corev1Api
  .gitignore
  README.md
  package-lock.json
  package.json
  typedoc.json
Labels: approved, cncf-cla: yes, lgtm, size/L
