Repository kubernetes-client/javascript, pull requests merged in 2019-11, with the labels that each got.

#366 Update OpenApi Generator to v4.1.3
  settings
Labels: approved, cncf-cla: yes, lgtm, size/XS

#363 Remove unused package
  examples/yaml-example.js
Labels: approved, cncf-cla: yes, lgtm, size/XS

#368 Fix bugs in programmatic cluster config. Add unit test.
  src/config.ts
  src/config_test.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#369 Add some missing error handling.
  src/watch.ts
  src/watch_test.ts
Labels: approved, cncf-cla: yes, lgtm, size/L

#371 Don't require client-secret in OIDC authentication.
  src/oidc_auth.ts
  src/oidc_auth_test.ts
Labels: approved, cncf-cla: yes, lgtm, size/S

#372 Add an export function for KubeConfigs. Add unit tests too.
  src/config.ts
  src/config_test.ts
  src/config_types.ts
Labels: approved, cncf-cla: yes, lgtm, size/M
