Repository kubernetes-client/javascript, pull requests merged in 2019-09, with the labels that each got.

#335 Oidc
  package-lock.json
  package.json
  src/oidc_auth.ts
  src/oidc_auth_test.ts
Labels: approved, cncf-cla: yes, lgtm, size/XL

#346 Fix packaging.
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#348 Rev diff dependency to handle security update.
  package-lock.json
Labels: approved, cncf-cla: yes, lgtm, size/S
