Repository kubernetes-client/javascript, pull requests merged in 2019-01, with the labels that each got.

#166 Improve coverage, fix some bugs.
  src/config.ts
  src/config_test.ts
  src/exec_auth.ts
  src/portforward.ts
  src/portforward_test.ts
Labels: approved, cncf-cla: yes, lgtm, size/XL

#154 Add a test for empty users.
  src/config_test.ts
  testdata/empty-user-kubeconfig.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#181 Add an example of how to hit raw URLs.
  examples/raw-example.js
Labels: approved, cncf-cla: yes, lgtm, size/S

#167 Implement OIDC Authentication Support
  src/oidc_auth.ts
  src/oidc_auth_test.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#160 Move types for node and http to 'dependencies' from 'devDependencies'
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#183 Add drubin and itowlson as a reviewers
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#185 Various small improvements
  .travis.yml
  README.md
  examples/typescript/attach/attach-example.ts
  examples/typescript/exec/exec-example.ts
  examples/typescript/port-forward/port-forward.ts
  examples/typescript/simple/example.ts
  examples/typescript/tsconfig.json
  examples/typescript/watch/watch-example.ts
  package.json
  src/package_test.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#186 Support insecure-skip-tls-verify as config option for port-forward
  src/config.ts
  src/config_test.ts
  src/web-socket-handler.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#180 Fix sending protocols for web sockets.
  examples/typescript/exec/exec-example.ts
  src/exec.ts
  src/exec_test.ts
  src/web-socket-handler.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#169 Add an initial watch cache implementation.
  examples/cache-example.js
  src/cache.ts
  src/cache_test.ts
  src/index.ts
  src/types.ts
Labels: approved, cncf-cla: yes, lgtm, size/L

#190 Rev. version to 0.8.0
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#191 Update package-lock too...
  package-lock.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#193 Update raw-example.js to use template strings
  examples/raw-example.js
Labels: approved, cncf-cla: yes, lgtm, size/XS

#197 Support commands with arguments in Exec
  src/exec.ts
  src/exec_test.ts
Labels: approved, cncf-cla: yes, lgtm, size/S
