Repository kubernetes-client/javascript, pull requests merged in 2019-06, with the labels that each got.

#260 Housekeeping: Fix npm audit
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#259 Improve release....
  build-package.sh
  package-lock.json
  package.json
  tsconfig.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#256 Specify swagger-codegen version to pull in optional header override
  settings
Labels: approved, cncf-cla: yes, lgtm, size/XS

#238 fixed bug on windows running cmd
  src/cloud_auth.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#270 Update to version 0.10.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#269 Fix examples
  examples/cache-example.js
  examples/example.js
  examples/in-cluster.js
  examples/namespace.js
  examples/typescript/simple/example.ts
  examples/yaml-example.js
Labels: approved, cncf-cla: yes, lgtm, size/S

#271 Add .editorconfig
  .editorconfig
  README.md
  tsconfig.json
  tslint.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#272 Fix example code in README.
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#273 Update to version 0.10.1
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#275 Fix request import in log.ts
  src/log.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#276 Update to version 0.10.2
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#267 Add support for multiple kubeconfigs in the KUBECONFIG env var.
  src/config.ts
  src/config_test.ts
  src/config_types.ts
  testdata/kubeconfig-2.yaml
  testdata/kubeconfig-dupe-cluster.yaml
  testdata/kubeconfig-dupe-context.yaml
  testdata/kubeconfig-dupe-user.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#278 Chore: Update dependencies due to security warning...
  package-lock.json
  package.json
  src/config.ts
Labels: approved, cncf-cla: yes, lgtm, size/XL

#280 Disable `allowSyntheticDefaultImports` and `esModuleInterop`
  src/config_test.ts
  src/integration_test.ts
  src/watch.ts
  tsconfig.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#277 Add basic informer functionality.
  examples/cache-example.js
  examples/typescript/informer/informer.ts
  src/cache.ts
  src/cache_test.ts
  src/index.ts
  src/informer.ts
  src/types.ts
Labels: approved, cncf-cla: yes, lgtm, size/XL

#286 Update to version 0.10.3
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#285 Remove extraneous log, add more tests.
  src/cache_test.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#284 fix Electron support
  .gitignore
  package.json
  src/cloud_auth.ts
  src/config.ts
  src/config_test.ts
  src/exec_auth.ts
  src/exec_auth_test.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#289 Switch from json-stream to byline.
  package-lock.json
  package.json
  src/watch.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#292 improve error handling in watch by checking response
  src/watch.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS
