Repository kubernetes-client/javascript, pull requests merged in 2020-07, with the labels that each got.

#476 Create examples/scale-deployment.js
  examples/scale-deployment.js
Labels: approved, cncf-cla: yes, lgtm, size/S

#477 Remove unnecessary assignment in constructor
  src/cache.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#482 Implement kubectl cp
  examples/typescript/cp/cp-example.ts
  examples/typescript/cp/test.txt
  package-lock.json
  package.json
  src/cp.ts
  src/cp_test.ts
  src/index.ts
  testdata/archive.txt
Labels: approved, cncf-cla: yes, lgtm, size/L

#483 Make watch path match listFn
  examples/cache-example.js
Labels: approved, cncf-cla: yes, lgtm, size/XS
