Repository kubernetes-client/javascript, pull requests merged in 2020-04, with the labels that each got.

#424 fix: add defaultHeaders field to ApiType interface
  src/config.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#431 Add a test for exec token caching and fix the implementation.
  src/config.ts
  src/config_test.ts
Labels: approved, cncf-cla: yes, lgtm, size/S

#433 add github action.
  .github/workflows/test.yml
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#434 Fix lint action, fix lint error.
  .github/workflows/test.yml
  src/config_test.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#436 Update package version.
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#437 [DOC] Show an example of creating an ingress
  examples/ingress.js
Labels: approved, cncf-cla: yes, lgtm, size/S
