Repository kubernetes-client/javascript, pull requests merged in 2020-02, with the labels that each got.

#407 Update to version 0.11.2
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#408 Apply authentication when streaming logs
  src/config.ts
  src/config_test.ts
  src/log.ts
Labels: approved, cncf-cla: yes, lgtm, size/S

#410 Fixed missing variable initialization
  src/web-socket-handler.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#412 Update coverage. Add more tests.
  src/web-socket-handler.ts
  src/web-socket-handler_test.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#417 Improve test coverage.
  src/config.ts
  src/config_test.ts
  src/file_auth_test.ts
  src/watch_test.ts
Labels: approved, cncf-cla: yes, lgtm, size/L

#415 Initial implementation of "top" command for nodes
  examples/top.js
  src/index.ts
  src/top.ts
  src/util.ts
  src/util_test.ts
Labels: approved, cncf-cla: yes, lgtm, size/L
