Repository kubernetes-client/javascript, pull requests merged in 2020-09, with the labels that each got.

#493 update ws
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#500 Add option to filter invalid items when loading a config
  src/config.ts
  src/config_test.ts
  src/config_types.ts
  testdata/empty-cluster-kubeconfig.yaml
  testdata/empty-context-kubeconfig.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#501 Update to version 0.12.2
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#502 Update the build status sticker to GH actions.
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#506 Move stream-buffers from devDependencies to dependencies
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#510 Update openid-client version to 4.1.1
  package-lock.json
  package.json
  tsconfig.json
Labels: approved, cncf-cla: yes, lgtm, size/XL
