Repository kubernetes-client/javascript, pull requests merged in 2020-11, with the labels that each got.

#538 Get ready for the 0.13.0 release.
  README.md
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#553 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#543 Update to version 0.13.1
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#546 fix tests on windows.
  src/config_test.ts
  src/exec_auth_test.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#555 split watch error and watch done handlers.
  src/cache.ts
  src/cache_test.ts
  src/watch.ts
  src/watch_test.ts
Labels: approved, cncf-cla: yes, lgtm, size/L

#526 Fix timeout on watch.js requestOptions
  src/watch.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS
