Repository kubernetes-client/javascript, pull requests merged in 2020-10, with the labels that each got.

#520 Add support for NodeJS version 14
  .github/workflows/test.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#521 Update cp.ts
  src/cp.ts
  src/cp_test.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#507 Require typedef in the style. Add some missing return types.
  src/cache.ts
  src/cloud_auth.ts
  src/config.ts
  src/exec_auth.ts
  src/file_auth.ts
  src/informer.ts
  src/oidc_auth.ts
  src/terminal-size-queue.ts
  src/watch.ts
  src/web-socket-handler.ts
  tslint.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#508 Add some constants and an example of patching resources.
  examples/patch-example.js
  src/index.ts
  src/patch.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#531 Fix formatting errors.
  src/patch.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#532 Update to version 0.12.3
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#533 Update owners file to move mbohlool to emeritus
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#535 Update to version 0.12.4
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/XS
