Repository kubernetes-client/javascript, pull requests merged in 2020-01, with the labels that each got.

#387 Update handlebars dependency.
  package-lock.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#391 Remove some unnecessary validation.
  src/config.ts
  src/config_test.ts
Labels: approved, cncf-cla: yes, lgtm, size/S

#388 Improve the OIDC auth to pull the expiration date from the token.
  package-lock.json
  package.json
  src/oidc_auth.ts
  src/oidc_auth_test.ts
Labels: approved, cncf-cla: yes, lgtm, size/L

#393 Add error handling to informer
  examples/typescript/informer/informer.ts
  src/cache.ts
  src/informer.ts
Labels: approved, cncf-cla: yes, lgtm, size/S

#394 Fix watch api missing Authentication when using an async Authenticator
  examples/typescript/watch/watch-example.ts
  src/cache.ts
  src/watch.ts
  src/watch_test.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#396 Fix watch to emit an error twice on error. Add tests.
  src/watch.ts
  src/watch_test.ts
Labels: approved, cncf-cla: yes, lgtm, size/S
