Repository kubernetes-client/javascript, pull requests merged in 2021-06, with the labels that each got.

#665 Update client libraries
  package-lock.json
Labels: approved, cncf-cla: yes, lgtm, size/XL

#667 Update our typescript settings.
  src/package_test.ts
  tsconfig.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#683 Update scale-deployment.js
  examples/scale-deployment.js
Labels: approved, cncf-cla: yes, lgtm, size/XS

#682 Update normalize-url dependency.
  package-lock.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#685 Upgrade `shelljs` to `0.8.4`
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/M
