Repository kubernetes-client/javascript, pull requests merged in 2021-04, with the labels that each got.

#613 Add a unit test to require registry.npm.js as the package registry.
  src/package_test.ts
Labels: approved, cncf-cla: yes, lgtm, size/S

#626 Update to version 0.14.2
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#628 Added filtering of empty paths in KUBECONFIG
  src/config.ts
  src/config_test.ts
Labels: approved, cncf-cla: yes, lgtm, size/S

#630 send keep-alive probes every 30 seconds to the server
  package-lock.json
  package.json
  src/watch.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#629 bump setup-node to v2
  .github/workflows/test.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#635 fix: remove dependency on net-keepalive
  package-lock.json
  package.json
  src/watch.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#645 Remove mode from typedoc config to comply with v0.20
  package-lock.json
  typedoc.json
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#647 Remove node 10, it has reached EOL, add node 16 to get us ready for the next LTS.
  .github/workflows/test.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS
