Repository kubernetes-client/javascript, pull requests merged in 2021-05, with the labels that each got.

#614 Add a CONNECT event to informer.
  src/cache.ts
  src/cache_test.ts
  src/informer.ts
Labels: approved, cncf-cla: yes, lgtm, size/L

#651 bump execa to v5.0.0
  package-lock.json
  package.json
  src/config.ts
  src/exec_auth.ts
  src/exec_auth_test.ts
Labels: approved, cncf-cla: yes, lgtm, size/XL

#646 Watch with labelSelector
  examples/typescript/informer/informer-with-label-selector.ts
  src/cache.ts
  src/cache_test.ts
  src/informer.ts
Labels: approved, cncf-cla: yes, lgtm, size/L

#631 Update to version 0.14.4
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#658 docs: Add note to readme around use multiple kubeconfigs
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
