Repository kubernetes-client/javascript, pull requests merged in 2021-03, with the labels that each got.

#597 cache: skip callback upon restart if object did not change
  src/cache.ts
  src/cache_test.ts
Labels: approved, cncf-cla: yes, lgtm, size/S

#601 Example - create job from cronjob in cluster
  examples/in-cluster-create-job-from-cronjob.js
Labels: approved, cncf-cla: yes, lgtm, size/M

#605 Use the public npm registry
  package-lock.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#606 Expose a public Informer.stop()
  src/cache.ts
  src/cache_test.ts
  src/informer.ts
Labels: approved, cncf-cla: yes, lgtm, size/L

#607 Use npm ci as safer install option for CI tests
  .github/workflows/test.yml
Labels: approved, cncf-cla: yes, size/XS

#615 Add a 'change' event to the informer.
  src/cache.ts
  src/cache_test.ts
  src/informer.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#616 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: approved, cncf-cla: yes, lgtm, size/M
