Repository kubernetes-client/javascript, pull requests merged in 2021-07, with the labels that each got.

#686 Update to version 0.15.1
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#690 Follow Log Example.
  examples/follow-logs.js
Labels: approved, cncf-cla: yes, lgtm, size/S

#688 Upgrade js-yaml to 4.1.0
  package-lock.json
  package.json
  src/config.ts
  src/yaml.ts
Labels: approved, cncf-cla: yes, lgtm, size/L

#692 Set current context namespace in loadFromCluster()
  src/config.ts
  src/config_test.ts
Labels: approved, cncf-cla: yes, lgtm, size/S

#698 docs: hosts autogenerated docs on GitHub Pages via Actions, updates README
  .github/workflows/deploy-docs.yml
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/M

#702 split cloud_auth into gcp and azure
  src/azure_auth.ts
  src/azure_auth_test.ts
  src/config.ts
  src/config_test.ts
  src/gcp_auth.ts
  src/gcp_auth_test.ts
Labels: approved, cncf-cla: yes, lgtm, size/XL
