Repository kubernetes-client/javascript, pull requests merged in 2021-01, with the labels that each got.

#573 Update to version 0.13.3
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#574 Update a bunch of dependencies. Fix code for new Typescript errors.
  package-lock.json
  package.json
  src/cache_test.ts
  src/object_test.ts
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#580 Preserve context from starting file
  src/config.ts
  src/config_test.ts
Labels: approved, cncf-cla: yes, lgtm, size/S

#576 cache: Fix connection leak.
  src/cache.ts
  src/cache_test.ts
  src/watch.ts
  src/watch_test.ts
Labels: approved, cncf-cla: yes, lgtm, size/L
