Repository kubernetes-client/javascript, pull requests merged in 2021-08, with the labels that each got.

#703 Replace callback with promise in Log
  examples/follow-logs.js
  src/log.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#712 catch parse error in edge case of Log response handling
  src/log.ts
Labels: cncf-cla: yes, size/XS, approved, lgtm

#711 Attempt to start list watch from last resourceVersion
  src/cache.ts
  src/cache_test.ts
  src/watch.ts
Labels: cncf-cla: yes, size/L, approved, lgtm
