Repository kubernetes-client/javascript, pull requests merged in 2021-02, with the labels that each got.

#584 Expose types from config_types.ts
  src/index.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#590 Update to version 0.14.1 & update version compatability table in readme
  README.md
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#591 Upgrade typedoc to latest.
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/L
