Repository kubernetes-client/javascript, pull requests merged in 2021-12, with the labels that each got.

#748 Expand the concept of the homeDir on Windows
  src/config.ts
  src/config_test.ts
Labels: cncf-cla: yes, size/L, approved, lgtm

#750 update compatibility table in readme
  README.md
Labels: cncf-cla: yes, size/S, approved, lgtm

#753 Fix expires-on case on Azure auth
  src/azure_auth.ts
  src/azure_auth_test.ts
Labels: cncf-cla: yes, size/S, approved, lgtm

#755 Fetch migration docs
  FETCH_MIGRATION.md
  README.md
Labels: cncf-cla: yes, size/M, approved, lgtm

#757 Add support for more quantity units
  src/top_test.ts
  src/util.ts
  src/util_test.ts
Labels: cncf-cla: yes, size/M, approved, lgtm
