Repository kubernetes-client/javascript, pull requests merged in 2022-07, with the labels that each got.

#834 Update compatability matrix.
  README.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#839 Fix interpolation in config.ts
  src/config.ts
Labels: cncf-cla: yes, size/XS, approved, lgtm

#840 Add comment about patching custom resources on apply example
  examples/typescript/apply/apply-example.ts
Labels: cncf-cla: yes, size/XS, approved, lgtm

#848 Add single pod metrics
  src/metrics.ts
  src/metrics_test.ts
Labels: cncf-cla: yes, size/M, approved, lgtm

#847 Move types to devDependencies
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/XXL, approved, lgtm
