Repository kubernetes-client/javascript, pull requests merged in 2022-08, with the labels that each got.

#854 Return strong types in generic client
  src/object.ts
  src/object_test.ts
Labels: cncf-cla: yes, size/L, approved, lgtm

#860 Fix formatting
  src/watch_test.ts
Labels: cncf-cla: yes, size/M, approved, lgtm

#861 Fix typedoc unable to find entry point
  package.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#868 Upgrade typescript to 4.7.4 and package-lock version to 2
  package-lock.json
  package.json
  src/azure_auth.ts
  src/gcp_auth.ts
  src/metrics_test.ts
  src/object.ts
  src/object_test.ts
  src/portforward_test.ts
Labels: cncf-cla: yes, size/XXL, approved, lgtm
