Repository kubernetes-client/javascript, pull requests merged in 2022-09, with the labels that each got.

#869 update config tests
  src/config.ts
  src/config_test.ts
  test/match-buffer.ts
Labels: cncf-cla: yes, size/M, approved, lgtm

#870 Enable release-1.x tests
  .github/workflows/codeql-analysis.yml
  .github/workflows/test.yml
  package-lock.json
  package.json
  src/cache_test.ts
  src/config.ts
  src/gcp_auth_test.ts
  src/integration_test.ts
  src/portforward_test.ts
  src/util_test.ts
  src/watch_test.ts
Labels: cncf-cla: yes, size/XXL, approved, lgtm

#872 Update example with correct parameters
  examples/patch-example.js
Labels: cncf-cla: yes, size/XS, approved, lgtm

#867 Rev package version to 0.17.1
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#884 Ignore post-abort request errors
  src/cache.ts
  src/cache_test.ts
  src/watch.ts
Labels: cncf-cla: yes, size/M, approved, lgtm

#874 update versions for next release.
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#888 Add `tls-server-name` to https requests if provided
  src/config.ts
  src/config_test.ts
Labels: cncf-cla: yes, size/M, approved, lgtm

#882 Defer loading of OIDC until it's actually used.
  src/config.ts
  src/oidc_auth_delayed.ts
  src/oidc_auth_delayed_test.ts
Labels: cncf-cla: yes, size/L, approved, lgtm
