Repository kubernetes-client/javascript, pull requests merged in 2022-06, with the labels that each got.

#814 fix: upgrade openid-client to 5.1.6
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/XL, approved, lgtm

#818 makeInformer returns Informer & ObjectCache
  src/informer.ts
Labels: cncf-cla: yes, size/XS, approved, lgtm

#810 Get ready for release 0.17.0
  README.md
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/S, approved, lgtm

#822 convert log to use fetch streaming
  src/log.ts
  src/log_test.ts
Labels: cncf-cla: yes, size/L, approved, lgtm

#823 Make the Informer interface more strict
  src/cache.ts
  src/informer.ts
Labels: cncf-cla: yes, size/M, approved, lgtm

#829 remove Object.ts and get unit tests runnable again
  src/azure_auth.ts
  src/gcp_auth_test.ts
  src/index.ts
  src/integration_test.ts
  src/metrics.ts
  src/object.ts
  src/object_test.ts
  src/portforward_test.ts
  src/top_test.ts
Labels: cncf-cla: yes, size/XXL, approved, lgtm

#830 Support to serialize MicroTime fields
  src/types.ts
Labels: cncf-cla: yes, size/XS, approved, lgtm

#820 Add support for tls-server-name
  src/config.ts
  src/config_test.ts
  src/config_types.ts
  testdata/tls-server-name-kubeconfig.yaml
Labels: cncf-cla: yes, size/M, approved, lgtm
