Repository kubernetes-client/javascript, pull requests merged in 2022-02, with the labels that each got.

#770 upgrades tar version from 6.0.2 to 6.1.11
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/S, approved, lgtm

#772 Add list method to generic KubernetesObjectApi
  src/object.ts
  src/object_test.ts
Labels: cncf-cla: yes, size/L, approved, lgtm

#779 feb 22 update
  FETCH_MIGRATION.md
Labels: cncf-cla: yes, size/M, approved, lgtm
