Repository kubernetes-client/javascript, pull requests merged in 2023-01, with the labels that each got.

#955 Copy the nodejs process.env rather than mutate the global state
  src/exec_auth.ts
Labels: cncf-cla: yes, size/XS, approved, lgtm

#962 add NetworkingV1 Ingress example
  examples/ingress.js
Labels: cncf-cla: yes, size/M, approved, lgtm

#965 support fieldSelector for Informer
  src/cache.ts
  src/cache_test.ts
  src/informer.ts
Labels: cncf-cla: yes, size/M, approved, lgtm

#873 Add a workflow to perform releases.
  .github/workflows/release.yml
Labels: cncf-cla: yes, size/S, lifecycle/stale, approved, lgtm

#966 Fix push script to be able to run without input and skip tagging.
  .github/workflows/release.yml
  push-package.sh
Labels: cncf-cla: yes, size/S, approved, lgtm
