Repository kubernetes-client/javascript, pull requests merged in 2023-07, with the labels that each got.

#1158 Remove underscore js
  package-lock.json
  package.json
  src/config_types.ts
  src/util.ts
Labels: cncf-cla: yes, size/M, approved, lgtm

#1164 Examples improvements
  README.md
  examples/cache-example.js
  examples/example.js
  examples/follow-logs.js
  examples/in-cluster-create-job-from-cronjob.js
  examples/in-cluster.js
  examples/ingress.js
  examples/namespace.js
  examples/patch-example.js
  examples/raw-example.js
  examples/scale-deployment.js
  examples/top.js
  examples/top_pods.js
  examples/typescript/apply/apply-example.ts
  examples/typescript/attach/attach-example.ts
  examples/typescript/exec/exec-example.ts
  examples/typescript/informer/informer-with-label-selector.ts
  examples/typescript/informer/informer.ts
  examples/typescript/port-forward/port-forward.ts
  examples/typescript/simple/example.ts
  examples/typescript/tsconfig.json
  examples/typescript/watch/watch-example.ts
  examples/yaml-example.js
  tslint.json
Labels: cncf-cla: yes, size/XL, approved, lgtm

#1170 Add KubernetesObjectApi for v1
  examples/typescript/apply/apply-example.ts
  src/index.ts
  src/object.ts
  src/object_test.ts
  src/patch.ts
Labels: cncf-cla: yes, size/XXL, approved, lgtm

#1169 Remove tmp-promise
  package-lock.json
  package.json
  src/cp.ts
  src/util.ts
Labels: cncf-cla: yes, size/L, approved, lgtm
