Repository kubernetes-client/javascript, pull requests merged in 2023-09, with the labels that each got.

#1255 FEAT: Adding support for multiple client
  src/config.ts
  src/config_test.ts
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1254 chore: add kubectl equivalent examples
  examples/kubectl/equivalents/namespace-create-yaml.js
  examples/kubectl/equivalents/namespace-create.js
  examples/kubectl/equivalents/namespace-list.js
  examples/kubectl/equivalents/pod-create.js
  examples/kubectl/equivalents/pod-filter-by-namespace.js
  examples/kubectl/equivalents/resourceQuota-create.js
  examples/kubectl/equivalents/resourceQuota-list.js
  examples/resources/namespace.yml
Labels: cncf-cla: yes, size/L, approved, lgtm

#1266 Update for release 0.19.0
  README.md
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/S, approved, lgtm

#1267 Fix a version update that I missed.
  package-lock.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1269 Add node 20 to our test matrix, remove node 14, fix test for node 20.
  .github/workflows/test.yml
  src/config.ts
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1268 Add an additional test for version synchronization
  src/package_test.ts
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1281 Update to version 0.20.0 and k8s 1.28 support
  README.md
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/S, approved, lgtm
