Repository kubernetes-client/javascript, pull requests merged in 2023-04, with the labels that each got.

#1033 fix: remove final refrences to request + fix tests
  .github/workflows/test.yml
  FETCH_MIGRATION.md
  package-lock.json
  package.json
  src/cache.ts
  src/cache_test.ts
  src/config.ts
  src/config_test.ts
  src/gen/apis/exception.ts
  src/log.ts
  src/metrics.ts
  src/watch.ts
  src/watch_test.ts
  test/match-buffer.ts
Labels: cncf-cla: yes, size/XXL, approved, lgtm

#1037 fix: casing of `applyToHttpsOptions`
  src/config.ts
  src/config_test.ts
  src/proto-client.ts
  src/web-socket-handler.ts
Labels: cncf-cla: yes, size/S, approved, lgtm

#1038 fix: casing of applyToHttpsOptions
  src/config.ts
  src/config_test.ts
  src/log.ts
  src/metrics.ts
  src/proto-client.ts
  src/watch.ts
  src/web-socket-handler.ts
Labels: cncf-cla: yes, size/M, approved, lgtm

#1044 docs: update fetch migration current state
  FETCH_MIGRATION.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1063 Update to rc2.
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/XS, approved
