Repository kubernetes-client/javascript, pull requests merged in 2023-11, with the labels that each got.

#1378 Update Kubernetes Version in README.md
  README.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1388 chore: run npm audit fix to update vulnerabile package
  .github/workflows/test.yml
  package-lock.json
Labels: cncf-cla: yes, size/XL, approved, lgtm

#1382 ci: dont annotate the git tag
  .github/workflows/release.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1312 docs: exec example
  examples/typescript/exec/exec-example.ts
Labels: cncf-cla: yes, size/XS, lgtm

#1435 ci: use node lts in deploy docs workflow
  .github/workflows/deploy-docs.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1436 fix: add support for tls-server-name in KubeConfig
  src/config.ts
  src/config_test.ts
  src/config_types.ts
  testdata/tls-server-name-kubeconfig.yaml
Labels: cncf-cla: yes, size/M, approved, lgtm

#1445 fix: Fix TypeError of topNodes
  src/top.ts
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1446 chore: adjust owners file to the current state
  OWNERS
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1444 ci: add release workflow for 1.x
  .github/workflows/release.yml
Labels: cncf-cla: yes, size/M, approved, lgtm
