Repository kubernetes-client/javascript, pull requests merged in 2023-12, with the labels that each got.

#1462 [release-1.x] chore: update owners file
  OWNERS
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1464 [release-1.x] ci: add generate javascript action
  .github/workflows/generate-javascript.yml
Labels: cncf-cla: yes, size/M, approved, lgtm

#1480 chore: switch from nyc to c8
  .github/workflows/test.yml
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/XXL, approved, lgtm

#1487 fix: do not overwrite current context
  src/config.ts
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1488 fix: do not overwrite current context
  src/config.ts
Labels: cncf-cla: yes, size/XS, approved, lgtm
