Repository kubernetes-client/javascript, pull requests merged in 2024-05, with the labels that each got.

#1671 Update README.md for new version.
  README.md
Labels: cncf-cla: yes, size/S, approved, lgtm

#1680 Fix tagging for releases.
  .github/workflows/release.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1687 Fix typos in FETCH_MIGRATION.md
  FETCH_MIGRATION.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1700 Cherry-Pick #1695
  src/cache.ts
  src/object.ts
  src/object_test.ts
  src/serializer.ts
  src/serializer_test.ts
  src/util.ts
Labels: cncf-cla: yes, size/L, approved, lgtm
