Repository kubernetes-client/javascript, pull requests merged in 2024-12, with the labels that each got.

#2088 web-socket-handler: fix type for TypeScript update
  src/web-socket-handler.ts
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2062 src: convert project from CJS to ESM
  package.json
  src/api.ts
  src/attach.ts
  src/attach_test.ts
  src/auth.ts
  src/azure_auth.ts
  src/azure_auth_test.ts
  src/cache.ts
  src/cache_test.ts
  src/config.ts
  src/config_test.ts
  src/cp.ts
  src/cp_test.ts
  src/exec.ts
  src/exec_auth.ts
  src/exec_auth_test.ts
  src/exec_test.ts
  src/file_auth.ts
  src/file_auth_test.ts
  src/gcp_auth.ts
  src/gcp_auth_test.ts
  src/health.ts
  src/health_test.ts
  src/index.ts
  src/informer.ts
  src/integration_test.ts
  src/log.ts
  src/log_test.ts
  src/metrics.ts
  src/metrics_test.ts
  src/object.ts
  src/object_test.ts
  src/oidc_auth.ts
  src/oidc_auth_test.ts
  src/package_test.ts
  src/portforward.ts
  src/portforward_test.ts
  src/proto-client.ts
  src/serializer.ts
  src/serializer_test.ts
  src/top.ts
  src/top_test.ts
  src/types.ts
  src/util.ts
  src/util_test.ts
  src/watch.ts
  src/watch_test.ts
  src/web-socket-handler.ts
  src/web-socket-handler_test.ts
  src/yaml_test.ts
  tsconfig.json
  version-check.js
Labels: cncf-cla: yes, size/L, approved, lgtm

#2091 Proxy url
  package-lock.json
  package.json
  src/config.ts
  src/config_test.ts
  src/config_types.ts
  src/web-socket-handler.ts
  testdata/kubeconfig-2.yaml
  testdata/kubeconfig-proxy-url.yaml
  testdata/kubeconfig.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm

#2106 Update generate repo commit in github action
  settings
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2107 Update generate-javascript.yml
  .github/workflows/generate-javascript.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2094 chore: add cjihrig to OWNERS
  OWNERS
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2112 src: move test directory under `src/`
  package.json
  src/attach_test.ts
  src/azure_auth_test.ts
  src/config_test.ts
  src/cp_test.ts
  src/exec_test.ts
  src/gcp_auth_test.ts
  src/test/call-awaiter.ts
  src/test/echo space.js
  src/test/index.ts
  src/test/match-buffer.ts
  src/test/resizable-writeable-stream-buffer.ts
  test/call-awaiter.ts
  test/match-buffer.ts
  tsconfig.json
Labels: cncf-cla: yes, size/L, approved, lgtm

#2113 Rev to 1.0.0 ready for release
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2114 Add the ability to push a non pre-release to NPM
  .github/workflows/release.yml
Labels: cncf-cla: yes, size/L, approved, lgtm

#2119 deps: remove colors override
  package.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2120 deps: remove unused dependencies
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/L, approved, lgtm

#2121 doc: remove CHANGELOG.md
  CHANGELOG.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2122 test: support testing transpiled code
  .github/workflows/test.yml
  package.json
  src/attach_test.ts
  src/config_test.ts
  src/cp_test.ts
  src/exec_test.ts
  src/test/index.ts
  src/test/match-buffer.ts
  tsconfig-with-tests.json
Labels: cncf-cla: yes, size/S, approved, lgtm

#2123 ci: set workflow permissions for release job
  .github/workflows/release.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2124 chore: add cjihrig to OWNERS
  OWNERS
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2111 Add proxy support
  package-lock.json
  package.json
  src/config.ts
  src/config_test.ts
  src/config_types.ts
  testdata/kubeconfig-proxy-url.yaml
  testdata/kubeconfig.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm

#2126 Fix proxy tests
  src/config_test.ts
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#2125 fix: KubernetesObjectSerializer::deserialize() should support list api
  src/serializer.ts
  src/serializer_test.ts
Labels: cncf-cla: yes, size/L, approved, lgtm

#2130 examples: fix kubectl examples for v1
  examples/kubectl/equivalents/apply.js
  examples/kubectl/equivalents/create.js
  examples/kubectl/equivalents/delete.js
  examples/kubectl/equivalents/get.js
Labels: cncf-cla: yes, size/M, approved, lgtm

#2132 Update test.yml to test main branch.
  .github/workflows/test.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm
