Repository kubernetes-client/javascript, pull requests merged in 2024-09, with the labels that each got.

#1872 Rev version to 0.22.0 prepare for release.
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1880 Fix cp promise returns by converting the exec callbacks into promises
  src/cp.ts
  src/cp_test.ts
  src/util.ts
  src/web-socket-handler.ts
  test/call-awaiter.ts
  testdata/archive.tgz
Labels: cncf-cla: yes, size/L, approved, lgtm

#1891 test: replace use of deprecated Buffer constructor
  src/config_test.ts
Labels: cncf-cla: yes, size/S, approved, lgtm

#1890 ci: test against node 22
  .github/workflows/test.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1892 ci: test against node 22
  .github/workflows/test.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1893 src: remove use of util.isUndefined()
  src/portforward.ts
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1888 chore: update ws
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1889 chore: update ws
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/XS, approved, lgtm
