Repository kubernetes-client/javascript, pull requests merged in 2024-03, with the labels that each got.

#1608 feat: add reexports for AbortError and FetchError from node-fetch to aid instanceof checks
  package-lock.json
  package.json
  src/index.ts
Labels: cncf-cla: yes, size/M, approved, lgtm

#1620 update openid-client
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1627 Update generate-javascript.yml
  .github/workflows/generate-javascript.yml
Labels: cncf-cla: yes

#1631 Update generate-javascript.yml
  .github/workflows/generate-javascript.yml
Labels: cncf-cla: yes, approved
