Repository kubernetes-client/javascript, pull requests merged in 2024-11, with the labels that each got.

#1999 [release-1.x] patch braces high vuln
  package-lock.json
Labels: cncf-cla: yes, size/M, approved, lgtm

#2006 chore: run format as pre-commit hook
  .husky/pre-commit
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/L, approved, lgtm

#2007 chore: run format as pre-commit hook
  .husky/pre-commit
  .husky/pre-push
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/XXL, approved, lgtm

#2019 test: clean up rejection and fail logic
  src/exec_auth_test.ts
  src/metrics_test.ts
  src/object_test.ts
  src/portforward_test.ts
  src/web-socket-handler_test.ts
Labels: cncf-cla: yes, size/L, approved, lgtm

#2025 bump jsonpath-plus
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2031 chore: bump jsonpath-plus allowed version range
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2032 chore: bump jsonpath-plus allowed version range
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2041 update deprecated husky command
  package.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2037 Add support for the v5 protocol
  src/web-socket-handler.ts
  src/web-socket-handler_test.ts
Labels: cncf-cla: yes, size/L, approved, lgtm

#2045 build(deps): bump cross-spawn from 7.0.3 to 7.0.5
  package-lock.json
Labels: cncf-cla: yes, size/S, approved, lgtm

#2046 makes exec_auth spawn the command asynchronously
  src/exec_auth.ts
  src/exec_auth_test.ts
Labels: cncf-cla: yes, size/L, approved, lgtm

#2035 Add Health class to call health check endpoints on current context
  src/health.ts
  src/health_test.ts
  src/index.ts
Labels: cncf-cla: yes, size/L, approved, lgtm

#2052 src: remove AbortSignal import
  src/log.ts
  src/watch.ts
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2053 src: replace Promise chains with async/await
  src/log.ts
  src/metrics.ts
  src/watch.ts
Labels: cncf-cla: yes, size/L, approved, lgtm

#2059 ci: update action versions, test node 23, unpin node 20
  .github/workflows/test.yml
Labels: cncf-cla: yes, size/M, approved, lgtm

#2063 deps: remove url-parse dependency
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/M, approved, lgtm

#2061 Add support for the v5 streaming protocol
  src/web-socket-handler.ts
  src/web-socket-handler_test.ts
Labels: cncf-cla: yes, size/L, approved, lgtm
