Repository kubernetes-client/javascript, pull requests merged in 2024-10, with the labels that each got.

#1898 deps: replace `byline` with `node:readline`
  package.json
  src/watch.ts
Labels: cncf-cla: yes, size/M, approved, lgtm

#1899 logs: add support for sinceTime option
  src/log.ts
  src/log_test.ts
Labels: cncf-cla: yes, size/M, approved, lgtm

#1900 fix: support multi-byte characters in WebSocket handler
  src/web-socket-handler.ts
  src/web-socket-handler_test.ts
Labels: cncf-cla: yes, size/M, approved, lgtm

#1906 deps: remove underscore dependency
  package-lock.json
  package.json
  src/config_types.ts
  src/util.ts
Labels: cncf-cla: yes, size/M, approved, lgtm

#1922 refactor Node core module imports
  examples/typescript/apply/apply-from-file-example.ts
  examples/typescript/exec/exec-example.ts
  examples/typescript/port-forward/port-forward.ts
  src/attach.ts
  src/auth.ts
  src/azure_auth.ts
  src/azure_auth_test.ts
  src/cache_test.ts
  src/config.ts
  src/config_test.ts
  src/config_types.ts
  src/cp.ts
  src/cp_test.ts
  src/exec.ts
  src/exec_auth.ts
  src/exec_auth_test.ts
  src/file_auth.ts
  src/file_auth_test.ts
  src/gcp_auth.ts
  src/gcp_auth_test.ts
  src/log.ts
  src/log_test.ts
  src/metrics_test.ts
  src/object_test.ts
  src/oidc_auth.ts
  src/oidc_auth_test.ts
  src/package_test.ts
  src/portforward.ts
  src/portforward_test.ts
  src/proto-client.ts
  src/terminal-size-queue.ts
  src/watch.ts
  src/watch_test.ts
  src/web-socket-handler.ts
  src/web-socket-handler_test.ts
  test/call-awaiter.ts
  test/match-buffer.ts
Labels: cncf-cla: yes, size/L, approved, lgtm

#1918 ci: use node LTS in workflows
  .github/workflows/generate-javascript.yml
  .github/workflows/release.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1919 ci: use node LTS in workflows
  .github/workflows/deploy-docs.yml
  .github/workflows/generate-javascript.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1920 chore: prepare patch release 0.22.1
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1923 refactor imports in src
  src/attach.ts
  src/attach_test.ts
  src/auth.ts
  src/azure_auth.ts
  src/cache_test.ts
  src/config.ts
  src/config_test.ts
  src/config_types.ts
  src/cp.ts
  src/cp_test.ts
  src/exec.ts
  src/exec_auth.ts
  src/exec_auth_test.ts
  src/file_auth.ts
  src/gcp_auth.ts
  src/integration_test.ts
  src/metrics_test.ts
  src/object_test.ts
  src/portforward.ts
  src/proto-client.ts
  src/top_test.ts
  src/watch_test.ts
  src/web-socket-handler.ts
  src/web-socket-handler_test.ts
  src/yaml.ts
Labels: cncf-cla: yes, size/L, approved, lgtm

#1934 Reset resource version
  src/cache.ts
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1936 Unit tests for #1934
  src/cache_test.ts
Labels: cncf-cla: yes, size/M, approved, lgtm

#1935 ci: set github token permission to write in release workflow
  .github/workflows/release.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1953 override whatwg-url dependency
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/M, approved, lgtm

#1963 chore(deps): move types to dev-deps
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/M, approved, lgtm

#1972 Switch from ts-node to tsx for tests
  .mocharc.json
  package-lock.json
  package.json
  test/mocha.opts
Labels: cncf-cla: yes, size/XL, approved, lgtm

#1973 Move from ts-node to tsx for tests
  .mocharc.json
  package-lock.json
  package.json
  test/mocha.opts
Labels: cncf-cla: yes, size/XL, approved, lgtm

#1974 Don't concatenate shell arguments.
  src/gcp_auth.ts
Labels: cncf-cla: yes, size/S, approved, lgtm, do-not-merge/invalid-commit-message

#1980 remove generated package.json file
  generate-client.sh
  src/gen/package.json
Labels: cncf-cla: yes, size/M, approved, lgtm

#1976 Add: deleteCollectionNamespacedCustomObject to support labelSelector
  .github/workflows/generate-javascript.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1994 Rev to new patch version.
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1995 Improve watch performance.
  src/cache.ts
  src/cache_test.ts
Labels: cncf-cla: yes, size/L, approved, lgtm

#1998 Update to version 0.22.3
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/XS, approved, lgtm
