Repository kubernetes-client/javascript, pull requests merged in 2025-04, with the labels that each got.

#2343 Add 1.1.x to README
  README.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2356 Update release.yml
  .github/workflows/release.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2357 Fix release.yml (again)
  .github/workflows/release.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2359 Revert "begin migration to native fetch()"
  package-lock.json
  package.json
  src/config.ts
  src/config_test.ts
  src/health.ts
  src/index.ts
  src/log.ts
  src/metrics.ts
  src/metrics_test.ts
  src/util.ts
  src/util_test.ts
  src/watch.ts
  tsconfig.json
Labels: cncf-cla: yes, size/XXL, approved, lgtm

#2351 fix: apply http agent if needed
  src/cache_test.ts
  src/config.ts
  src/config_test.ts
  src/watch_test.ts
  testdata/kubeconfig-proxy-url.yaml
Labels: cncf-cla: yes, size/M, approved, lgtm

#2360 Prepare for release 1.1.2
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2367 Reintroduce timeout and keep-alive for watch requests to match client-go
  src/watch.ts
  src/watch_test.ts
Labels: cncf-cla: yes, size/L, approved, lgtm

#2389 watch: prevent done callback from being called twice on connection loss
  src/watch.ts
  src/watch_test.ts
Labels: cncf-cla: yes, size/M, approved, lgtm

#2373 config: support username impersonation
  src/config.ts
  src/config_test.ts
  src/config_types.ts
Labels: cncf-cla: yes, size/M, approved, lgtm

#2402 Move to tar-fs.
  package-lock.json
  package.json
  src/cp.ts
Labels: cncf-cla: yes, size/L, approved, lgtm
