Repository kubernetes-client/javascript, pull requests merged in 2025-09, with the labels that each got.

#2602 fix: respect NODE_TLS_REJECT_UNAUTHORIZED environment variable
  src/config.ts
  src/config_test.ts
  testdata/certs/test-cert.pem
  testdata/certs/test-key.pem
Labels: cncf-cla: yes, size/L, approved, lgtm

#2638 Update the base devcontainer image and add docker support
  .devcontainer/devcontainer.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2635 feat: allow to set the cwd in copyFromPod for use in tar
  src/cp.ts
  src/cp_test.ts
Labels: cncf-cla: yes, size/M, approved, lgtm
