Repository kubernetes-client/javascript, pull requests merged in 2025-05, with the labels that each got.

#2400 fix(object): properly serialize objects on create/replace/patch
  src/object.ts
  src/object_test.ts
Labels: cncf-cla: yes, size/L, approved, lgtm

#2417 Rev package versions in preparation for release.
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2418 Update README.md
  README.md
Labels: cncf-cla: yes, size/S, approved, lgtm

#2419 ci: test on Node v24
  .github/workflows/test.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2429 Cherry-pick in two watch changes from the 0.x branch, clean up tests, fix list -> resourceVersion handling
  src/cache.ts
  src/cache_test.ts
Labels: cncf-cla: yes, size/L, approved, lgtm

#2433 feat: add model registry to object serializer
  src/serializer.ts
  src/serializer_test.ts
Labels: cncf-cla: yes, size/L, approved, lgtm

#2442 chore: readd ws as a dependency
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/S, approved, lgtm

#2446 fix: readd AbortError export
  src/index.ts
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2454 update package versions in preparation for release
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/XS, approved, lgtm
