Repository kubernetes-client/javascript, pull requests merged in 2025-01, with the labels that each got.

#2135 chore: update remaining release-1.x branch references
  .github/workflows/codeql-analysis.yml
  pre-check.sh
Labels: cncf-cla: yes, size/M, approved, lgtm

#2134 chore: fix markdown in issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: cncf-cla: yes, size/S, approved, lgtm

#2129 Fix type definition for KubernetesObjectApi.read()
  src/object.ts
  src/object_test.ts
Labels: cncf-cla: yes, size/S, approved, lgtm

#2136 examples: fix typescript examples for v1
  examples/typescript/apply/apply-example.ts
  examples/typescript/apply/apply-from-file-example.ts
  examples/typescript/attach/attach-example.ts
  examples/typescript/cp/cp-example.ts
  examples/typescript/informer/informer.ts
  examples/typescript/patch/patch-example.ts
  examples/typescript/simple/example.ts
Labels: cncf-cla: yes, size/M, approved, lgtm

#2137 examples: fix remaining examples for v1
  examples/cache-example.js
  examples/follow-logs.js
  examples/in-cluster-create-job-from-cronjob.js
  examples/in-cluster.js
  examples/patch-example.js
  examples/raw-example.js
  examples/scale-deployment.js
  examples/top.js
  examples/yaml-example.js
Labels: cncf-cla: yes, size/M, approved, lgtm

#2138 examples: port missing examples from master to main
  examples/kubectl/equivalents/namespace-create-yaml.js
  examples/kubectl/equivalents/namespace-create.js
  examples/kubectl/equivalents/namespace-list.js
  examples/kubectl/equivalents/namespace.yaml
  examples/kubectl/equivalents/pod-create.js
  examples/kubectl/equivalents/pod-filter-by-namespace.js
  examples/kubectl/equivalents/resourceQuota-create.js
  examples/kubectl/equivalents/resourceQuota-list.js
Labels: cncf-cla: yes, size/L, approved, lgtm

#2139 export `ApiConstructor`-type
  src/config.ts
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2144 websocket: do not close when protocol supports it
  src/web-socket-handler.ts
  src/web-socket-handler_test.ts
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2145 chore: migrate dependabot config from master branch
  .github/dependabot.yml
Labels: cncf-cla: yes, size/S, approved, lgtm

#2162 deps: replace tslint with typescript-eslint
  README.md
  eslint.config.js
  examples/typescript/simple/example.ts
  examples/typescript/tslint.json
  package-lock.json
  package.json
  src/attach_test.ts
  src/azure_auth_test.ts
  src/cache_test.ts
  src/config.ts
  src/config_test.ts
  src/cp_test.ts
  src/exec_auth_test.ts
  src/exec_test.ts
  src/gcp_auth_test.ts
  src/gen/models/ObjectSerializer.ts
  src/object.ts
  src/object_test.ts
  src/oidc_auth_test.ts
  src/portforward_test.ts
  src/terminal-size-queue.ts
  src/test/match-buffer.ts
  src/top.ts
  src/util.ts
  src/watch.ts
  src/watch_test.ts
  src/web-socket-handler_test.ts
  tsconfig.json
  tslint.json
Labels: cncf-cla: yes, size/XXL, approved, lgtm

#2166 deps: remove whatwg-url override
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/L, approved, lgtm

#2167 test: replace chai with node:assert
  README.md
  eslint.config.js
  package-lock.json
  package.json
  src/attach_test.ts
  src/azure_auth_test.ts
  src/cache_test.ts
  src/config_test.ts
  src/exec_auth_test.ts
  src/exec_test.ts
  src/file_auth_test.ts
  src/gcp_auth_test.ts
  src/health_test.ts
  src/integration_test.ts
  src/log_test.ts
  src/metrics_test.ts
  src/object_test.ts
  src/oidc_auth_test.ts
  src/package_test.ts
  src/portforward_test.ts
  src/serializer_test.ts
  src/test/match-buffer.ts
  src/top_test.ts
  src/util_test.ts
  src/watch_test.ts
  src/web-socket-handler_test.ts
  src/yaml_test.ts
Labels: cncf-cla: yes, size/XXL, approved, lgtm

#2188 Update README.md
  README.md
Labels: cncf-cla: yes, size/S, approved, lgtm

#2191 Improve loadFromCluster testing
  src/config_test.ts
Labels: cncf-cla: yes, size/S, approved, lgtm

#2194 doc: remove FETCH_MIGRATION.md
  FETCH_MIGRATION.md
Labels: cncf-cla: yes, size/M, approved, lgtm

#2192 examples: fix confusing patch example code
  examples/patch-example.js
  examples/typescript/patch/patch-example.ts
Labels: cncf-cla: yes, size/S, approved, lgtm
