Repository kubernetes-client/javascript, pull requests merged in 2025-02, with the labels that each got.

#2195 src: update for node-fetch v3 compatibility
  src/config.ts
  src/config_test.ts
  src/log.ts
  src/watch.ts
  src/watch_test.ts
Labels: cncf-cla: yes, size/M, approved, lgtm

#2203 ci: update permissions for CodeQL action
  .github/workflows/codeql-analysis.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2216 docs: correct directory and set entryPointStrategy
  package.json
  typedoc.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2224 Fix a bug where an error on request wouldn't propogate.
  src/cache.ts
  src/cache_test.ts
Labels: cncf-cla: yes, size/M, approved, lgtm

#2230 Add a devcontainer, since the default for codespaces is node 16 :0
  .devcontainer/devcontainer.json
  .github/dependabot.yml
Labels: cncf-cla: yes, size/S, approved, lgtm

#2231 Improve coverage for cache.ts
  src/cache_test.ts
Labels: cncf-cla: yes, size/L, approved, lgtm

#2260 include source maps in npm pack
  package.json
Labels: cncf-cla: yes, size/S, approved, lgtm

#2265 bump jsonpath-plus minimum version to 10.3.0
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2272 Improve coverage by adding unit tests for log.ts
  package.json
  src/log.ts
  src/log_test.ts
Labels: cncf-cla: yes, size/L, approved, lgtm

#2274 improve coverage for top.ts by covering topNodes.
  eslint.config.js
  src/top_test.ts
  src/util.ts
Labels: cncf-cla: yes, size/L, approved, lgtm

#2276 Update README.md
  README.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2277 Add testing for /readyz
  src/health.ts
  src/health_test.ts
Labels: cncf-cla: yes, size/L, approved, lgtm
