Repository kubernetes-client/javascript, pull requests merged in 2025-03, with the labels that each got.

#2283 Improve exec_auth_test coverage
  src/exec_auth_test.ts
Labels: cncf-cla: yes, size/M, approved, lgtm

#2284 Fixes
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/L, approved, lgtm

#2288 Improve coverage and testability of config.ts
  src/config.ts
  src/config_test.ts
Labels: cncf-cla: yes, size/M, approved, lgtm

#2294 test: handle process.env in config_test.ts
  src/config_test.ts
Labels: cncf-cla: yes, size/S, approved, lgtm

#2295 doc: update branch in README
  README.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2296 Prepare for 1.0.1 release
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2298 Update to release 1.1.0
  .github/workflows/release.yml
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2302 Revisions needed for no non-erasable types
  src/cache.ts
  src/config_types.ts
  src/object.ts
  src/oidc_auth.ts
  src/patch.ts
  src/top.ts
  src/util.ts
  src/web-socket-handler.ts
Labels: cncf-cla: yes, size/L, approved, lgtm

#2303 Add eslint config to prevent introduction of non-erasable changes
  eslint.config.js
  package-lock.json
  package.json
  src/object_test.ts
  src/test/match-buffer.ts
Labels: cncf-cla: yes, size/M, approved, lgtm

#2304 Update pre-push
  .husky/pre-push
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2305 docs: generate docs for the whole `gen` directory
  package.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2311 Add the ability to inject authenticators.
  src/config.ts
  src/config_test.ts
Labels: cncf-cla: yes, size/M, approved, lgtm

#2332 Prepare for v1.1.1 patch release
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2333 begin migration to native fetch()
  package-lock.json
  package.json
  src/config.ts
  src/config_test.ts
  src/health.ts
  src/index.ts
  src/log.ts
  src/metrics.ts
  src/metrics_test.ts
  src/util.ts
  src/util_test.ts
  src/watch.ts
Labels: cncf-cla: yes, size/XL, approved, lgtm

#2340 test: replace mocha with node:test
  .mocharc.json
  README.md
  package-lock.json
  package.json
  src/attach_test.ts
  src/azure_auth_test.ts
  src/cache_test.ts
  src/config_test.ts
  src/cp_test.ts
  src/exec_auth_test.ts
  src/exec_test.ts
  src/file_auth_test.ts
  src/gcp_auth_test.ts
  src/health_test.ts
  src/integration_test.ts
  src/log_test.ts
  src/metrics_test.ts
  src/middleware_test.ts
  src/object_test.ts
  src/oidc_auth_test.ts
  src/package_test.ts
  src/portforward_test.ts
  src/serializer_test.ts
  src/top_test.ts
  src/util_test.ts
  src/watch_test.ts
  src/web-socket-handler_test.ts
  src/yaml_test.ts
Labels: cncf-cla: yes, size/XXL, approved, lgtm
